project_id = "iyeljkdrypcxvljebqtn"

[functions.validate-access-token]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.create-sindico]
verify_jwt = true

[functions.create-super-admin]
verify_jwt = false
