project_id = "iyeljkdrypcxvljebqtn"

[functions.validate-access-token]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.create-sindico]
verify_jwt = false

[functions.create-super-admin]
verify_jwt = false

[functions.test-whatsapp-connection]
verify_jwt = false

[functions.send-whatsapp-test]
verify_jwt = false

[functions.notify-sindico-defense]
verify_jwt = false

[functions.notify-resident-decision]
verify_jwt = false

[functions.generate-invoices]
verify_jwt = false
